Sprint 2
putiniyama/middle.messenger.praktikum.yandex pull request #4
Opened 2022-10-08 21:34 UTC by putiniyama

2022-10-09 04:58 UTC, agadoev requested changes
Привет, @putiniyama 
Спасибо за работу! Я внимательно все посмотрел и оставил комментарии, которые нужно будет поправить

2022-10-09 04:58 UTC, agadoev commented on .gitignore
> +\n
Эта строка тут точно нужна?

2022-10-09 04:58 UTC, agadoev commented on package.json
> +		"start": "parcel build src/index.html --no-cache --public-url ./ && node ./server.js"
Нужно добавить скрипт для запуска eslint'a и stylelint'a. Зависимости есть, но они не используются

2022-10-09 04:58 UTC, agadoev commented on src/api.ts
> +}
Подумай над тем, чтобы использовать union вместо enum'a. Union не транспилируется в объект, как enum, и на не нужно дублировать код (сейчас для каждого элемента перечисления дублируется строка). Подробнее можно почитать [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

2022-10-09 04:58 UTC, agadoev commented on src/api.ts
> +	data?: any
важной частью протокола HTTP являются заголовки. Давай добавим их сюда и будем учитывать их при формировании запроса

2022-10-09 04:58 UTC, agadoev commented on src/api.ts
> +	get(
Нужны еще методы для put, post и delete

2022-10-09 04:58 UTC, agadoev commented on src/components/button/button.css
> +	background-color: #d9d9d9;
Цвета должны находиться в отдельном файле в переменных

2022-10-09 04:58 UTC, agadoev commented on src/components/button/button.ts
> +*/
Закомментированный код лучше не держать в репозитории. Он загрязняет кодовую базу и отвлекает внимание.

2022-10-09 04:58 UTC, agadoev commented on src/components/controlledInput/controlledInput.ts
> +	type?: 'text' | 'password' | 'email'
хорошее решение использовать union 👍

2022-10-09 04:58 UTC, agadoev commented on src/components/controlledInput/controlledInput.ts
> +	class?: string
Что, если нужно будет передать несколько классов? предлагаю тут использовать ```string[]```

2022-10-09 04:58 UTC, agadoev commented on src/core/renderDOM.ts
> +  const root = document.querySelector('#app');
предлагаю вынести css селектор в аргументы функции. Это позволит избежать хардкода внутри этой фукнции.

2022-10-09 04:58 UTC, agadoev commented on src/helpers/validateForm.ts
> +			} else {
Этот функционал можно вынести в отдельную небольшую функцию, которая проверяет, является ли строка пустой. Вообще всю валидацию можно свести к набору небольших функций-валидаторов, каждая из которых проверяет что-то одно, например
```
empty = (value: string): boolean =>
email = (value: string): boolean =>
```

потом эти функции можно легко комбинировать между собой. Таким образом код будет более гибким и менее запутанным
```
if (empty(input)) {
 /* some action */
}
if (!email(input)) {
  /* some action */
}
```

и т.к. у всех таких функций-валидаторов одна и та же сигнатура, можно выделить ее в тип
```
type TValidator = (value: string) => boolean
```

в общем пространство для рефакторинга есть и я накидал вариантов

2022-10-09 04:58 UTC, agadoev commented on src/pages/login/login.ts
> +				if (this.element?.querySelector('input[name="login"]') === inputEl) {
Этот querySelector выглядит довольно сложным. Легко допустить ошибку в селекторе. На самом деле можно вообще его не использовать, если при инициализации LoginPage, сохранить ссылку на этот инпут

2022-10-09 04:58 UTC, agadoev commented on src/pages/login/login.ts
> +				) as HTMLInputElement
Нужно стараться избегать явного приведения типов там, где этого избежать можно. В данном случае можно написать так:
```suggestion
				const passwordEl = this.element?.querySelector<HTMLInputElement>(
					'input[name="password"]')
```

2022-10-09 04:58 UTC, agadoev commented on src/pages/password-change/password-change.ts
> +				}
кажется я уже видел этот код, только он был для login и отличался только селектором. Это похоже на нарушение DRY. Попробуй вынести этот функционал в функцию и параметризовать ее селектором

2022-10-09 10:50 UTC, putiniyama commented on .gitignore
> +\n
удалил

2022-10-09 10:51 UTC, putiniyama commented on .gitignore
> +\n
удалил

2022-10-09 14:53 UTC, putiniyama commented on src/components/button/button.ts
> +*/
удалил

2022-10-09 18:40 UTC, putiniyama commented on src/components/button/button.css
> +	background-color: #d9d9d9;
сделал через postcss-import переменные из фала variables.css

2022-10-09 20:13 UTC, putiniyama commented on package.json
> +		"start": "parcel build src/index.html --no-cache --public-url ./ && node ./server.js"
Добавил

2022-10-09 20:15 UTC, putiniyama commented on src/components/controlledInput/controlledInput.ts
> +	class?: string
Исправил

2022-10-10 20:43 UTC, putiniyama commented on src/api.ts
> +}
исправил

2022-10-10 22:28 UTC, putiniyama commented on src/api.ts
> +	data?: any
добавил

2022-10-10 22:28 UTC, putiniyama commented on src/api.ts
> +	get(
добавил

2022-10-10 22:41 UTC, putiniyama commented on src/core/renderDOM.ts
> +  const root = document.querySelector('#app');
готово)

2022-10-10 22:43 UTC, putiniyama commented on src/pages/login/login.ts
> +				if (this.element?.querySelector('input[name="login"]') === inputEl) {
через refs?

2022-10-12 20:36 UTC, putiniyama commented on src/api.ts
> +}
сделано

2022-10-12 20:37 UTC, putiniyama commented on src/api.ts
> +	data?: any
сделано

2022-10-12 21:52 UTC, putiniyama commented on src/helpers/validateForm.ts
> +			} else {
готово

2022-10-13 22:40 UTC, putiniyama commented on src/pages/password-change/password-change.ts
> +				}
поменял подход)

2022-10-13 22:40 UTC, putiniyama commented on src/pages/login/login.ts
> +				) as HTMLInputElement
изменил

2022-10-13 23:47 UTC, putiniyama commented
Доброй ночи, случайно забыл поменять ссылку в readme 
https://roaring-melba-e7a5e0.netlify.app/

2022-10-15 05:23 UTC, agadoev approved these changes
Привет, @putiniyama 
Спасибо за правки! Работа принимается, удачи в следующем спринте :)

2022-10-15 08:57 UTC, merged